### ISSUE TITLE
Cannot find module '../build/Release/agora_node_ext'

### ISSUE THREAD

**Issue by StitchC** [AgoraIO-Community/Agora-RTC-SDK-for-Electron#6]
when i import sdk to my project throw this error

**Comment by menthays** [comment]
You mean using esm import? Which platform do you use? Commonly after you run `npm install` our sdk will be automatically built by node-gyp and generate your mssing file. Could you give more details?

**Comment by StitchC** [comment]
yes i use esm import,here is my code

![image](https://user-images.githubusercontent.com/21286819/41831370-2b6f4bde-7879-11e8-8846-c01eb5f6670b.png)

import and init 

![image](https://user-images.githubusercontent.com/21286819/41831393-5b436ad4-7879-11e8-84ad-f520b8f891b7.png)

**Comment by StitchC** [comment]
and this project i use electron + vue

**Comment by menthays** [comment]
Em, I find that you are using methods in our web sdk. However this repo is an electron intergration for our native sdk(for both darwin and win32). So I recommend you to run `npm install agora-rtc-sdk` instead and have a try.

**Comment by menthays** [comment]
You can find a simple JS api doc at (here)[https://github.com/AgoraIO-Community/Agora-RTC-SDK-for-Electron/blob/dev/2.2.1/docs/apis.md]. 
And since this repo is a wrapper for our native sdk, you can also go to (agora document center)[https://docs.agora.io/en/2.3.1] to have a look at windows/Mac api.

And we have a complete demo in E-edu at (ARD-eEducation-with-Electron)[https://github.com/AgoraIO/ARD-eEducation-with-Electron] built with react/webpack/electron.

Apart form these, we are improving our js api doc / comment / test coverage, and will commit a quick start demo recently for this sdk.

**Comment by menthays** [comment]
We have released a quickstart boilerplate for using this sdk. Go to #8 for more detail.
