### ISSUE TITLE
Quickstart boilerplate for using Agora-RTC-SDK-for-Electron

### ISSUE THREAD

**Issue by menthays** [AgoraIO-Community/Agora-RTC-SDK-for-Electron#8]
We have newly provide a quickstart boilerplate for using this sdk. Have a try and welcome for advices or pr.
**Agora-Electron-Quickstart:**
https://github.com/AgoraIO-Community/Agora-Electron-Quickstart

**Comment by StitchC** [comment]
Thank you very much, now i can see my local video, but i can't set the local video view size, could you tell my how to do that ?

**Comment by plutoless** [comment]
@StitchC if you are talking about the view container size - it's basically html5 and you can easily modify it with css. Or otherwise you are talking about the actual size of the video stream (to make it higher resolution) you may look into setVideoProfile function. The documentation of this function can be found at agora's official website.

https://docs.agora.io/cn/2.2.1/product/Interactive%20Broadcast/Product%20Overview/revisionhistory_live_windows?platform=Windows
